### ISSUE TITLE
iis_pool start action isn't working

### ISSUE THREAD

**Issue by kenny-evitt** [chef-cookbooks/iis#114]
Here's my pool resource in my recipe:

```
iis_pool "DB Necromancer" do
  runtime_version "4.5"
  pipeline_mode :Integrated
  action [:add, :start]
end
```

I was able to start the pool by running *appcmd* from a Windows Command Prompt window:

`appcmd start apppool "DB Necromancer"`

**Comment by kenny-evitt** [comment]
Actually, disregard this – something is stopping the pool.

**Comment by kenny-evitt** [comment]
Also the `runtime_version` isn't correct.

**Comment by kenny-evitt** [comment]
Here's my pool resource now:

```
iis_pool "DB Necromancer" do
  runtime_version "4.0"
  action [:add, :start]
end
```

The pool is created when the recipe is first run but the pool isn't started; the knife output:

```
...
snydevel =======================================================================
=========
snydevel Error executing action `start` on resource 'iis_pool[DB Necromancer]'
snydevel =======================================================================
=========
snydevel
snydevel Mixlib::ShellOut::ShellCommandFailed
snydevel ------------------------------------
snydevel Expected process to exit with [0], but received '4312'
snydevel ---- Begin output of C:\Windows\System32\inetsrv\appcmd.exe start apppo
ol "DB Necromancer" ----
snydevel STDOUT: ERROR ( hresult:800710d8, message:Command execution failed.
snydevel The object identifier does not represent a valid object.
snydevel  )
snydevel STDERR:
snydevel ---- End output of C:\Windows\System32\inetsrv\appcmd.exe start apppool
 "DB Necromancer" ----
snydevel Ran C:\Windows\System32\inetsrv\appcmd.exe start apppool "DB Necromance
r" returned 4312
snydevel
snydevel Cookbook Trace:
snydevel ---------------
snydevel c:/chef/cache/cookbooks/iis/providers/pool.rb:116:in `block in class_fr
om_file'
snydevel
snydevel Resource Declaration:
snydevel ---------------------
snydevel # In c:/chef/cache/cookbooks/recp-db-necromancer/recipes/default.rb
snydevel
snydevel  24: iis_pool "DB Necromancer" do
snydevel  25:   runtime_version "4.0"
snydevel  26:   action [:add, :start]
snydevel  27: end
snydevel  28:
snydevel
snydevel Compiled Resource:
snydevel ------------------
snydevel # Declared in c:/chef/cache/cookbooks/recp-db-necromancer/recipes/defau
lt.rb:24:in `from_file'
snydevel
snydevel iis_pool("DB Necromancer") do
snydevel   action [:add, :start]
snydevel   updated true
snydevel   retries 0
snydevel   retry_delay 2
snydevel   guard_interpreter :default
snydevel   cookbook_name "recp-db-necromancer"
snydevel   recipe_name "default"
snydevel   runtime_version "4.0"
snydevel   pool_name "DB Necromancer"
snydevel end
snydevel
snydevel [2015-02-11T15:19:57-05:00] INFO: Running queued delayed notifications
before re-raising exception
snydevel [2015-02-11T15:19:57-05:00] ERROR: Running exception handlers
snydevel [2015-02-11T15:19:57-05:00] ERROR: Exception handlers complete
snydevel [2015-02-11T15:19:57-05:00] FATAL: Stacktrace dumped to c:/chef/cache/c
hef-stacktrace.out
snydevel [2015-02-11T15:19:57-05:00] INFO: Sending resource update report (run-i
d: c3ff6156-a293-4ae0-b9cc-8d6ca099392a)
snydevel [2015-02-11T15:19:58-05:00] FATAL: Mixlib::ShellOut::ShellCommandFailed
: iis_pool[DB Necromancer] (recp-db-necromancer::default line 24) had an error:
Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but rec
eived '4312'
snydevel ---- Begin output of C:\Windows\System32\inetsrv\appcmd.exe start apppo
ol "DB Necromancer" ----
snydevel STDOUT: ERROR ( hresult:800710d8, message:Command execution failed.
snydevel The object identifier does not represent a valid object.
snydevel  )
snydevel STDERR:
snydevel ---- End output of C:\Windows\System32\inetsrv\appcmd.exe start apppool
 "DB Necromancer" ----
snydevel Ran C:\Windows\System32\inetsrv\appcmd.exe start apppool "DB Necromance
r" returned 4312
```

On subsequent runs, the pool is started fine.

Based on the error message `The object identifier does not represent a valid object.`, I'm guessing the pool creation hasn't entirely completed when the pool-start command is issued.

**Comment by EasyAsABC123** [comment]
the command returned 4312 which is `ERROR ( message:Cannot find requested collection element. )`

Something isn't working right for you i'll run your script here in a second, and update to your chef version

**Comment by EasyAsABC123** [comment]
@kenny-evitt this is working with the latest version master branch version, running your script on chef version `*** Chef 11.12.4 ***`

**Comment by kenny-evitt** [comment]
@EasyAsABC123 I'll test with the latest version and let you know the results.

**Comment by EasyAsABC123** [comment]
@kenny-evitt hey! any news on this?

**Comment by kenny-evitt** [comment]
@EasyAsABC123 I just tested this via Chef Zero. The app pool is created and started on my local computer but the chef-client output indicates that it failed to start the application pool:

```
...
  * iis_pool[DB Necromancer] action start[2015-03-27T12:54:45-04:00] INFO: Proce
ssing iis_pool[DB Necromancer] action start (recp-db-necromancer::default line 3
0)

================================================================================

Error executing action `start` on resource 'iis_pool[DB Necromancer]'
================================================================================


Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '4312'
---- Begin output of C:\Windows\System32\inetsrv\appcmd.exe start apppool "DB Ne
cromancer" ----
STDOUT: ERROR ( hresult:800710d8, message:Command execution failed.
The object identifier does not represent a valid object.
 )
STDERR:
---- End output of C:\Windows\System32\inetsrv\appcmd.exe start apppool "DB Necr
omancer" ----
Ran C:\Windows\System32\inetsrv\appcmd.exe start apppool "DB Necromancer" return
ed 4312
...
```

I'd guess that the pool creation might not have finished before the start command is issued.

Do you need or want me to test this on the actual 'production' computer?

**Comment by EasyAsABC123** [comment]
@kenny-evitt hey! no it should work in Chef -Z (chef zero).  that's how I test it using vagrant, this is apparently a race condition in appcmd.

which version of windows are you using?
which version of iis are you using?
have you updated appcmd?

Let me know the above, this might require rewriting this LWRP to use WMI.

**Comment by kenny-evitt** [comment]
I'm running Windows 7 and IIS 6.1. I don't remember updating *appcmd* – how can I check?

[I ran into trouble with a build task that needed to wait until an IIS site stopped](http://stackoverflow.com/a/29034323/173497). Unfortunately, *appcmd* definitely seems to return before the commands or requests made with it have completed. I ended-up writing a small PowerShell snippet to poll the `appcmd list` output:

```
C:\Windows\System32\inetsrv\appcmd.exe stop site "siteName"

do { Start-Sleep -s 1; $siteInfo = C:\Windows\System32\inetsrv\appcmd.exe list site "siteName" } until ($siteInfo -match "state:Stopped")
```

**Comment by EasyAsABC123** [comment]
It looks like this was fixed at some point in append but I don't know when that point was so it will likely make sense to only do these checks if the chef client run is using that version or older.  

This will take a bat script test with each version of app me until the issue doesn't present itself.  Theoretically we could request people update to that version and remove support for older versions of appcmd. I'll put this on my todo list for while I'm at chef conf

**Comment by EasyAsABC123** [comment]
@kenny-evitt can you install IIS 7 and see if the issue persists?

I'm going to have to write a lot of code to figure out exactly when this issue was resolved.  In the meantime your look that is just waiting until the SITE exists will work but it in a coding sense has "smell" to it.

**Comment by kenny-evitt** [comment]
@EasyAsABC123 sorry; I read the version info incorrectly earlier. I already *am* running IIS 7, version 7.5.7600.16385. The *appcmd.exe* file has the same version as IIS.

**Comment by EasyAsABC123** [comment]
@kenny-evitt that's awesome news because it was confusing that you were utilizing iis 6.  A lot of this is design choices, if powershell will be used or dsc or wmi or if we stick with appcmd.  I'd presume for compatibility the latter but honestly they are all a means to an end.  I'll look into providing a patch for this soon.

Promise :)

**Comment by EasyAsABC123** [comment]
@kenny-evitt if you don't mind can you test the above feature branch?

**Comment by kenny-evitt** [comment]
@EasyAsABC123 I *may* have tested the feature branch just now. If I did so – correctly – then I ran into a *similar* error; see below.

Note that it's the *site* that failed to start this time, not the application pool.

I wrote "may have tested the feature branch" because I had some trouble installing the feature branch. I tried using the *[knife-github-cookbooks](https://github.com/websterclay/knife-github-cookbooks)* plugin. [Incidentally, someone just commented that the plugin is outdated and, indeed, no commits have been made to the *master* branch of the plugin's GitHub repo since 2011!] I seem to have been able to manually workaround the problem I ran into tho. It seemed like the problem was due to the plugin generating a `git commit ...` command that didn't work because of its use of single quotes instead of double quotes. I ran the command manually, replacing the quote characters, and it ran without issue.

```
...
  * iis_site[DB Necromancer] action start[2015-04-07T16:57:11-04:00] INFO: Proce
ssing iis_site[DB Necromancer] action start (recp-db-necromancer::default line 3
5)

================================================================================

Error executing action `start` on resource 'iis_site[DB Necromancer]'
================================================================================


Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0, 42], but received '4312'
---- Begin output of C:\Windows\System32\inetsrv\appcmd.exe start site /site.nam
e:"DB Necromancer" ----
STDOUT: ERROR ( hresult:800710d8, message:Command execution failed.
The object identifier does not represent a valid object.
 )
STDERR:
---- End output of C:\Windows\System32\inetsrv\appcmd.exe start site /site.name:
"DB Necromancer" ----
Ran C:\Windows\System32\inetsrv\appcmd.exe start site /site.name:"DB Necromancer
" returned 4312

Resource Declaration:
---------------------
# In i:/.chef/local-mode-cache/cache/cookbooks/recp-db-necromancer/recipes/defau
lt.rb

 35: iis_site "DB Necromancer" do
 36:   path "#{node['iis']['pubroot']}\\db-necromancer"
 37:   port 84
 38:   application_pool "DB Necromancer"
 39:   action [:add, :start]
 40: end
 41:

Compiled Resource:
------------------
# Declared in i:/.chef/local-mode-cache/cache/cookbooks/recp-db-necromancer/reci
pes/default.rb:35:in `from_file'

iis_site("DB Necromancer") do
  action [:add, :start]
  updated true
  retries 0
  retry_delay 2
  guard_interpreter :default
  cookbook_name "recp-db-necromancer"
  recipe_name "default"
  path "C:\\inetpub\\db-necromancer"
  port 84
  application_pool "DB Necromancer"
  site_name "DB Necromancer"
  protocol :http
end

[2015-04-07T16:57:12-04:00] INFO: Running queued delayed notifications before re
-raising exception

Running handlers:
[2015-04-07T16:57:12-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-04-07T16:57:12-04:00] ERROR: Exception handlers complete
[2015-04-07T16:57:12-04:00] FATAL: Stacktrace dumped to i:/.chef/local-mode-cach
e/cache/chef-stacktrace.out
Chef Client failed. 1 resources updated in 23.248325 seconds
[2015-04-07T16:57:12-04:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: iis_sit
e[DB Necromancer] (recp-db-necromancer::default line 35) had an error: Mixlib::S
hellOut::ShellCommandFailed: Expected process to exit with [0, 42], but received
 '4312'
---- Begin output of C:\Windows\System32\inetsrv\appcmd.exe start site /site.nam
e:"DB Necromancer" ----
STDOUT: ERROR ( hresult:800710d8, message:Command execution failed.
The object identifier does not represent a valid object.
 )
STDERR:
---- End output of C:\Windows\System32\inetsrv\appcmd.exe start site /site.name:
"DB Necromancer" ----
Ran C:\Windows\System32\inetsrv\appcmd.exe start site /site.name:"DB Necromancer
" returned 4312
```

**Comment by EasyAsABC123** [comment]
@kenny-evitt you can just download the zip file from https://github.com/opscode-cookbooks/iis/archive/hotfix-appcmd_bug_sync.zip then upload it to your chef server.  I don't think you have the latest because it should of `Chef::Log.error("Failed to start in 5 seconds")`

**Comment by EasyAsABC123** [comment]
@kenny-evitt  we can also try to do the following
```ruby
 35: iis_site "DB Necromancer" do
 36:   path "#{node['iis']['pubroot']}\\db-necromancer"
 37:   port 84
added:  retries 5
added:  retry_delay 2
 38:   application_pool "DB Necromancer"
 39:   action [:add, :start]
 40: end
```

**Comment by kenny-evitt** [comment]
@EasyAsABC123 it seemed to work – the *hotfix-appcmd_bug_sync* branch, not adding the 'retry' attributes. I added the dependency for the branch using Berkshelf and re-tested using Chef Zero.

**Comment by EasyAsABC123** [comment]
@ksubrama hey, so...can you spend some time looking at this code? I know it works and I know what it does, however I think that we would want the `retry` and `retry_delay` over this code.

**Comment by EasyAsABC123** [comment]
@kenny-evitt I have another idea for this and will be posting the code once i've resolved #163

**Comment by EasyAsABC123** [comment]
@kenny-evitt I've been testing a lot on this, and with IIS 8.5 and windows 8...these issues don't exist...

I'm going to try to spend some time testing your OS and IIS version

**Comment by kenny-evitt** [comment]
@EasyAsABC123 thanks! I'm happy to continue testing.

**Comment by kenny-evitt** [comment]
@EasyAsABC123 Any updates?

**Comment by EasyAsABC123** [comment]
I haven't been able to replicate, there were errors on 2003 windows server but I don't have a copy of that anymore.

**Comment by kenny-evitt** [comment]
@EasyAsABC123 Windows Server 2003 is no longer supported (by Chef), so that seems reasonable to disregard. If you don't have access to a Windows 7 box either, it doesn't seem like there's any reason to keep this open. Anyone else that runs into it can pick from several viable workarounds already mentioned in previous comments.

**Comment by kenny-evitt** [comment]
@EasyAsABC123 Thanks for looking into this anyways :smile:

**Comment by EasyAsABC123** [comment]
@kenny-evitt  I have windows 7 images...non that are chef-kitchen so...if you have one and are willing to share so I can test and resolve i'm more than happy to work on it otherwise the time to solve doesn't seem worth it

**Comment by kenny-evitt** [comment]
@EasyAsABC123 I don't have an image to share so let's punt on this indefinitely.
