### ISSUE TITLE
mod_aspnet does not work remotely with server 2012

### ISSUE THREAD

**Issue by tophercullen** [chef-cookbooks/iis#157]
There's an issue with the windows_feature_dism provider (see https://github.com/opscode-cookbooks/windows/issues/196) when installing NetFx3 remotely. Powershell works, dism does not. NetFx3 is required for the mod_aspnet recipe. However, the recipe is written to only support dism, which doesn't work with the dependency NetFx3.

**Comment by EasyAsABC123** [comment]
@tophercullen hello,
i'm not sure I completely understand the concern or the request.

The referred example is closed and I believe their solution is the same here.
