### ISSUE TITLE
Unable to add_default_documents using iis_root

### ISSUE THREAD

**Issue by JaBurd** [chef-cookbooks/iis#222]
I am attempting to add index.php to my iis setup via the following cookbook directive.  IIS server 8.5 on Windows Server 2012 r2

Perhaps my implementation is off?

    # Add index.php to default documents
    iis_root 'add_php' do
      add_default_documents ['index.php']
      action :add
    end
           ================================================================================
           Error executing action `add` on resource 'iis_root[add_php]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `stderr' for #<String:0x3111630>

           Resource Declaration:
           ---------------------
           # In C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/aw-app/recipes/webapp.rb

            18: iis_root 'add_php' do
            19:   add_default_documents ['index.php']
            20:   action :add
            21: end
            22:

           Compiled Resource:
           ------------------
           # Declared in C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/aw-app/recipes/webapp.rb:18:in `from_file'

           iis_root("add_php") do
             action [:add]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :iis_root
             cookbook_name "aw-app"
             recipe_name "webapp"
             add_default_documents ["index.php"]
             default_documents ["Default.htm", "Default.asp", "index.htm", "index.html", "iisstart.htm", "default.aspx"]
             default_documents_enabled true
             mimeType='application/octet-stream'", "fileExtension='.der',mimeType='application/x-x509-ca-cert'",
             "fileExtension='.dib',mimeType='image/bmp'", "fileExtension='.dir',mimeType='application/x-director'", 
             .....Writes every mimeType for some reason.......
             "fileExtension='.xsn',mimeType='application/octet-stream'", "fileExtension='.xtp',mimeType='application/octet-stream'",
             "fileExtension='.xwd',mimeType='image/x-xwindowdump'", "fileExtension='.z',mimeType='application/x-compress'",
             "fileExtension='.zip',mimeType='application/x-zip-compressed'"]
           end

       Running handlers:
       [2015-11-18T15:48:21-05:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-11-18T15:48:21-05:00] ERROR: Exception handlers complete
       [2015-11-18T15:48:21-05:00] FATAL: Stacktrace dumped to C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 2 resources updated in 80.863571 seconds
       [2015-11-18T15:48:21-05:00] FATAL: NoMethodError: iis_root[add_php] (aw-app::webapp line 18) had an error: NoMethodError: undefined method `stderr' for #<String:0x3111630>

**Comment by EasyAsABC123** [comment]
running tests right now, brb

**Comment by EasyAsABC123** [comment]
@JaBurd good catch currently there is a bug in `iis_root` that makes it 100% broken. Working on it right now

**Comment by EasyAsABC123** [comment]
@JaBurd the fix has been created, a new release will be made sortly.
All tests passed - check

Once the build is successful, i'll merge it to master
