### ISSUE TITLE
Question - Can cookbook deploy ssl cert?

### ISSUE THREAD

**Issue by spuder** [chef-cookbooks/iis#226]
It is common to offload your ssl encrypt/decrypt to a load balancer. How would you add a ssl certificate directly to a node? 

Looking at the cookbook, it doesn't appear to natively support adding a ssl certificate. 

http://www.awesomeideas.net/post/How-to-configure-SSL-on-IIS7-under-Windows-2008-Server-Core.aspx

Having never added a cert before, I'm trying to determine best practices for deploying on IIS. Can this cookbook do this? Should the cookbook be able to do this? Or is this something typically handled externally like through group policy?

**Comment by EasyAsABC123** [comment]
Similar to #221

**Comment by EasyAsABC123** [comment]
@spuder please move your good statement and knowledge to that issue
