### ISSUE TITLE
Can not install dotnet 4.5.2 over winrm

### ISSUE THREAD

**Issue by tophercullen** [chef-cookbooks/iis#227]
All the ways that i know of to install dotnet 4.5.2 require WUSA, which is not allowed for remote shells/connections. This includes the "offline" installer. As such it is not possible to install it using normal means.

http://blogs.technet.com/b/sus/archive/2012/10/30/kb-windows-update-standalone-installer-wusa-returns-0x5-error-access-denied-when-deploying-msu-files-through-winrm-and-windows-remote-shell.aspx

**Comment by EasyAsABC123** [comment]
@tophercullen .net isn't part of iis, https://supermarket.chef.io/cookbooks/ms_dotnet45

it is a separate cookbook, as it should be since neither require the other

**Comment by tophercullen** [comment]
I don't think that is entirely true. In order to register new version of .net, IIS needs to be installed and you would need to know the path/version of the framework. I'm also fairly certain you can not install the .net mods via the features without a framework being installed. I can't confirm as all the servers I have access to have it installed as part of the base image.
