### ISSUE TITLE
iis_module support for native modules

### ISSUE THREAD

**Issue by pierrecdn** [chef-cookbooks/iis#232]
### Environment: 
Windows/2008r2 and 2012r2
IIS/7.5 and 8.5

### Scenario:
Trying to install a native module, provided through a .dll
According to http://www.iis.net/learn/get-started/introduction-to-iis/iis-modules-overview, we have to install the native library before being able to enable it either for a specific application or globally

### Steps to suceed:
Provide `iis_module :install` and `iis_module :uninstall`actions in the provider

**Comment by EasyAsABC123** [comment]
@pierrecdn whenever you are ready do a PR so we can bring this into master.

**Comment by EasyAsABC123** [comment]
merged
