### ISSUE TITLE
Unlock attribute within section

### ISSUE THREAD

**Issue by surrealchemist** [chef-cookbooks/iis#241]
In some cases you may need to unlock an attribute (this is IIS configuration attribute I am talking about not chef attribute) within a section in the configuration editor, but I only see options to unlock a section.

For example, in my case I need to go into "system.webServer/httpErrors" and unlock the "defaultPath" attribute so the application can override it. It doesn't look like appcmd has a way to do it, but I found some powershell code that would allow me to do it (Not sure if this is included without installing anything extra):

```
powershell_script 'Unlock the httpErrors defaultPath attribute' do
  code <<-EOH
  Remove-WebConfigurationLock -Filter "system.webServer/httpErrors/@defaultPath"
  EOH
end
```

Perhaps this would be a more efficient way to edit the global config than appcmd and allow for more features.

**Comment by spuder** [comment]
appcmd is able to do locking / unlocking. I'm not sure if this is the same unlocking that you are referring to. 

https://github.com/chef-cookbooks/iis/pull/208#issuecomment-137277938

Eventually I'd like to add more of the appcmd commands. If appcmd unlock works the same as Remove-WebConfigurationLock it should be a pretty feature to add.

**Comment by EasyAsABC123** [comment]
@surrealchemist if this fixes it 
```
%windir%\System32\inetsrv\appcmd unlock config -section:system.webserver/httperrors
```

then the chef code would be
```ruby
iis_section 'unlocks httpErrors for webserver' do
  section 'system.webserver/httperrors'
  action :unlock
end
```

**Comment by EasyAsABC123** [comment]
will be testing this soon

**Comment by tas50** [comment]
@EasyAsABC123 Did you ever get a chance to test this issue?

**Comment by EasyAsABC123** [comment]
@tas50 i've been waiting for the original poster to respond.  I wasn't able to replicate, but I suppose i can try to replicate again.

**Comment by surrealchemist** [comment]
Sorry I never replied. Unfortunately I am no longer working at this company and on this project so I'm not really able to test at this point myself.

**Comment by EasyAsABC123** [comment]
@surrealchemist no worries, thanks for reporting the issue.  i'll work on replicating it locally for me.

**Comment by spuder** [comment]
This is still on my backlog of things to work on.

**Comment by EasyAsABC123** [comment]
waiting until iis_section is on the block for re-write, at that time this will have tests

**Comment by EasyAsABC123** [comment]
This can be done with, test will be added soon...this isn't idempotent, closing issue
```ruby
iis_section 'unlocks httpErrors for webserver' do
  section 'system.webserver/httperrors'
  action :unlock
end

iis_config 'change @httpErrors' do
  cfg_cmd '"MACHINE/WEBROOT/APPHOST/" -section:"system.webServer/httpErrors" -lockAttributes:"allowAbsolutePathsWhenDelegated" -commit:apphost'
  action :set
end
```
