### ISSUE TITLE
iis_pool uses case-sensitive comparison for name

### ISSUE THREAD

**Issue by SteveLowe** [chef-cookbooks/iis#242]
The iis_pool resource treats app pool name as case sensitive, but it is not.

If the app pool you are trying to create/edit already exists, but with a different case name, iis_pool will try to create a new one with the new case name. This fails as appcmd will report the pool already exists.

Chef reports this error:
```
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
iis_pool[Test] (c:/chef/local-mode-cache/cache/cookbooks/cookbook/resources/webapp.rb line 45) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '183'
---- Begin output of C:\Windows\System32\inetsrv\appcmd.exe add apppool /name:"Test" /managedRuntimeVersion:v4.0 /commit:"MACHINE/WEBROOT/APPHOST" ----
STDOUT: ERROR ( message:Failed to add duplicate collection element "Test". )
STDERR:
---- End output of C:\Windows\System32\inetsrv\appcmd.exe add apppool /name:"Test" /managedRuntimeVersion:v4.0 /commit:"MACHINE/WEBROOT/APPHOST" ----
Ran C:\Windows\System32\inetsrv\appcmd.exe add apppool /name:"Test" /managedRuntimeVersion:v4.0 /commit:"MACHINE/WEBROOT/APPHOST" returned 183
```

Looking at the code, iis_site suffers from the same problem.

**Comment by manjukk** [comment]
Im getting this error while creating a site in IIS.
[0mMixlib::ShellOut::ShellCommandFailed[0m
------------------------------------[0m
Expected process to exit with [0, 42], but received '183'
[0m---- Begin output of C:\Windows\System32\inetsrv\appcmd.exe start site /site.name:"WebAppChef" ----
[0mSTDOUT: ERROR ( hresult:800700b7, message:Command execution failed.

**Comment by EasyAsABC123** [comment]
@manjukk please create a separate issue for this, also it appears that command is correct and thereby the site either doesn't exist or there is a race condition that is unaccounted for.  Please create a separate issue for either case.
