### ISSUE TITLE
Can't set recycle_at_time to default

### ISSUE THREAD

**Issue by youngjl1** [chef-cookbooks/iis#247]
By default IIS does not recycle at a certain time. It would be nice to be able to enforce that by setting recycle_at_time to :default or something.

**Comment by youngjl1** [comment]
To clarify, I don't see any automated way of clearing out a recyle_at_time once it's been set.

**Comment by EasyAsABC123** [comment]
@youngjl1 so you want to set a recycle_at_time for a specific application pool?

And you want a what to clear them?

**Comment by youngjl1** [comment]
I guess I want a way to make sure there is no recycle time set, a way to enforce a certain state. Right now if someone sets a recycle time (through IIS cookbook or manually) there's no way in IIS cookbook to reset to default state where there is no recycle time.

Right now recycle_at_time accepts a string "d:hh:mm;ss." I was suggesting something like you set it to :default and it clears out any existing recycle times.

**Comment by EasyAsABC123** [comment]
@youngjl1 if you could test the added functionality in the new branch it would be appreciated.  From there it will be merged to master if successful.

Thanks
