### ISSUE TITLE
Handling failures with iis_config

### ISSUE THREAD

**Issue by Jakauppila** [chef-cookbooks/iis#251]
I'm using the _iis_config_ resource to define a periodic recycle time with the following:

```
iis_config "/section:system.applicationHost/applicationPools /+\"applicationPoolDefaults.recycling.periodicRestart.schedule.[value='02:00:00']\"" do
    action :set
end
```

This works the first time, but if I run the recipe again once it's already configured, I get the following error:

```
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '183'
---- Begin output of C:\Windows\System32\inetsrv\appcmd.exe set config /section:system.applicationHost/applicationPools +"applicationPoolDefaults.recycling.periodicRestart.schedule.[value='02:00:00']" ----
STDOUT: ERROR ( message:New add object missing required attributes. Cannot add duplicate collection entry of type 'add' with unique key attribute 'value' set to '02:00:00'    . )
STDERR:
---- End output of C:\Windows\System32\inetsrv\appcmd.exe set config /section:system.applicationHost/applicationPools /+"applicationPoolDefaults.recycling.periodicRestart.schedule.[value='02:00:00']"---
Ran C:\Windows\System32\inetsrv\appcmd.exe set config /section:system.applicationHost/applicationPools /+"applicationPoolDefaults.recycling.periodicRestart.schedule.[value='02:00:00']" returned 183
```

What's the best way to handle this error?

**Comment by EasyAsABC123** [comment]
`iis_config` is not idempotent, meaning everytime chef-client runs (30
minutes) it will be attempting to re run the above command.

a lot of people are using powershell to protect this with an if, but for
your request, it sounds like the scheduling logic needs to also be in
`iis_root` and not just `iis_pool` with regards to `recycle_at_time`.

**Comment by Jakauppila** [comment]
Okay, guess I didn't realize it wasn't idempotent.

Is there any plans to add an additional provider that utilizes the *-WebConfigurationProperty cmdlets for the resources or do I just need to roll my own _powershell_script_ for it?

**Comment by EasyAsABC123** [comment]
The current plan is to build a new system completely using the DSC from
microsoft which wraps the appcmd and powershell.  This branch isn't started
yet, but will be coming in the future,  in the meantime adding this to
`iis_root` isn't a huge task if that is the request.

**Comment by Jakauppila** [comment]
Yeah, that'd probably be the easiest thing to do right now.

**Comment by EasyAsABC123** [comment]
Closing as not fixing in this version
