### ISSUE TITLE
Maximum File Size

### ISSUE THREAD

**Issue by kalapakim** [chef-cookbooks/iis#257]
### I'm trying to set the Maximum File Size (in bytes) for the default website.

**The following is how I'm trying to do it..**
```
# Configure IIS logging
iis_site 'Default Web Site' do
  log_period :Daily
  log_truncsize 3000000
  site_id 1
  bindings 'http/*:80:,net.tcp/808:*,net.pipe/*,net.msmq/localhost,'\
           'msmq.formatname/localhost,https/*:443:'
  action :config
end
```

**I've also tried like:**

```
log_truncsize 3_000_000
```

**either way, the setting is not set...**

![image](https://cloud.githubusercontent.com/assets/6277786/13622232/f19a83a2-e562-11e5-95e8-c4f232721681.png)

**Please let me know what I'm missing.**

Thank You!!

**Comment by EasyAsABC123** [comment]
@kalapakim what size are you trying to set the file to? It has to be greater than 1MB and less than 4GB...it is in bytes (might change this to MB for simplicity...

So if you want to set it to say 4MB it would be:
```ruby
# Configure IIS logging
iis_site 'Default Web Site' do
  log_period :Daily
  log_truncsize 4194304
  site_id 1
  bindings 'http/*:80:,net.tcp/808:*,net.pipe/*,net.msmq/localhost,'\
           'msmq.formatname/localhost,https/*:443:'
  action :config
end
```

this should work
1024 * 1024 * 4 = 4MB

**Comment by EasyAsABC123** [comment]
Looks  like rubocop  likes every 3 digits to be separated with a `_`

**Comment by kalapakim** [comment]
You know what I figured it out, I was trying to verify it's settings in the UI and found that i would be in the applicationHost.config file, which was getting set correctly. I just thought it would be reflected in the Logging view of the UI of IIS Manager. Thanks!!!

**Comment by EasyAsABC123** [comment]
Sounds good, closing this issue...feel free to open it back up if something changes
