### ISSUE TITLE
tag cleanup

### ISSUE THREAD

**Issue by spuder** [chef-cookbooks/iis#263]
The git tags are mildly inconsistent. 

4.1.2 and 4.1.3 don't have the 'v' in front of them. 

4.1.6 has a capital 'V' instead of the more traditional lowercase 'v'. Not sure if that is on purpose. 

While the git commandline is case insensitive, github tag sorting is case sensitive. 

![screenshot 2016-03-18 13 38 19](https://cloud.githubusercontent.com/assets/242382/13889938/b909ba0e-ed0e-11e5-8e50-22c23f87cb5b.png)

**Comment by tas50** [comment]
Unfortunately once the tags are created we really can't remove them.  There are more than likely users out there pinned to the old tags.

**Comment by spuder** [comment]
What about adding a new tag "v4.1.6" that points to the same commit as "V4.1.6". That way it would atleast show up in order in github.
