### ISSUE TITLE
v4.1.6 has wrong metadata.rb

### ISSUE THREAD

**Issue by spuder** [chef-cookbooks/iis#264]
4.1.6 still has 4.1.5 inside the metadata.rb. See this commit: 

https://github.com/chef-cookbooks/iis/blob/V4.1.6/metadata.rb#L7

So if you are using chef-zero, or pointing your berks to 4.1.6 via git tags, you actually get 4.1.5

**Comment by EasyAsABC123** [comment]
Updated to v4.1.7, closing this as there isn't much I can do and v4.1.6 has multiple bugs that are resolved in 4.1.7

**Comment by tas50** [comment]
We had some metadata issues.  Sorry about that
