### ISSUE TITLE
Default Value for smp_processor_affinity_mask invalid

### ISSUE THREAD

**Issue by fuel-wlightning** [chef-cookbooks/iis#268]
When running a php cookbook which depends on iis, you get the following running kitchen converge:

> Deprecated features used!
>          Default value 4294967295 is invalid for property smp_processor_affinity_mask of resource iis_pool. In Chef 13 this will become an error: Option smp_processor_affinity_mask must be a kind of [Bignum]!  You passed 4294967295.. at 1 location:
>            - /tmp/kitchen/cookbooks/iis/resources/pool.rb:76:in `class_from_file'
>          Default value 4294967295 is invalid for property smp_processor_affinity_mask_2 of resource iis_pool. In Chef 13 this will become an error: Option smp_processor_affinity_mask_2 must be a kind of [Bignum]!  You passed 4294967295.. at 1 location:
>            - /tmp/kitchen/cookbooks/iis/resources/pool.rb:77:in `class_from_file'

This is using 4.1.6 version of iis cookbook. This happens regardless of iis being utilized (outside of including the php cookbook)

**Comment by EasyAsABC123** [comment]
This is fixed in master #267 #266 #265

**Comment by spuder** [comment]
I'm still seeing this in 4.1.7

**Comment by jesperrojestal** [comment]
Also seeing on master branch from php cookbook on linux that has it as dependency. Maybe 64-bit system related? 
Also on 64-bit 0xffffffff (all 32 bits masked) are Fixnum, Bignum starts at 2**62 for some reason for Fixnum. Float on the other hand goes all the way to 2**1023.0 without resulting in Float::INFINITY and will never be Bignum on the other hand.

**Comment by EasyAsABC123** [comment]
sounds like the solution is to change these to floats

**Comment by spuder** [comment]
Indeed, float does get rid of the warnings. 

Should the attribute take both BigNum and Float, or just Float? 

bignum and float

    attribute :smp_processor_affinity_mask, kind_of: [BigNum, Float], default: 4_294_967_295.0

float

    attribute :smp_processor_affinity_mask, kind_of: Float, default: 4_294_967_295.0

**Comment by EasyAsABC123** [comment]
Float is fine just make sure we do a floor still, add that PR whenever you can
