### ISSUE TITLE
Push to supermarket

### ISSUE THREAD

**Issue by spuder** [chef-cookbooks/iis#271]
Github has version 4.1.7
Supermarket is only at 4.1.6

Any plans to push 4.1.7 ?

**Comment by EasyAsABC123** [comment]
@spuder i don't control the supermarket version, @tas50 normally pushes it.  But he might be doing any number of things.

**Comment by spuder** [comment]
@tas50 could we get a supermarket push?

**Comment by spuder** [comment]
The smp_processor mask fix didn't make it in time for 4.1.7. 

Could we cut a 4.1.8 release and push it to the supermarket?

**Comment by tas50** [comment]
Done
