### ISSUE TITLE
Error passing array of commands to iis_config

### ISSUE THREAD

**Issue by bradwilliamson** [chef-cookbooks/iis#274]
Cookbook version

[4.1.8]

Chef-client version

[12.9.38]

Platform Details

[Windows 2008 R2 SP1 64bit]

Scenario:

[I am attempting to pass an array of commands to iis_config to allow ISAPI ASP.NETv 4.0.30319 filters to be enabled. I run the commands below manually on the node using appcmd & it works ]

Steps to Reproduce:

[Have .net framework 4.0 installed on 2008 R2 where ASP.NET 4.0 ISAPI filters show up. They will be set to not allowed by default.]

Expected Result:

[What are you expecting to happen as the consequence of above reproduction steps?]

Actual Result:

[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

![errorchefclientrun](https://cloud.githubusercontent.com/assets/13142011/15000734/a0d1e840-1157-11e6-9f1c-d7ae1d78d154.PNG)

Here is a GIST link to the part of my recipe that passes the array of commands to iis_config

https://gist.github.com/bradwilliamson/ddc235a3976bf7b560c0c529534ac79d

**Comment by EasyAsABC123** [comment]
@bradwilliamson can you open the file `iis/resources/config.rb` and look for `actions :config, :clear, :set
` this is the only place actions are defined... and the error you are getting is that the action you passed doesn't exist.

also when I just run the first command as this library will i get the following error:
```
C:\Windows\System32\inetsrv>appcmd.exe set config /section:isapicgiRestriction /[path="%windir%/Microsoft.NET/Framework/v4.0.30319/aspnet_isapi.dll"].allowed:True
ERROR ( message:Malformed collection indexer; format is [@position,name='value',name2='value2',...].  The @position specifier is optional, and be '@start', '@end', or '@N' where N is a numeric index into the collection. )
```

**Comment by bradwilliamson** [comment]
@EasyAsABC123  Thank you for the response.  I was using an example on the cookbook page. I was attempting to pass an array of commands from an older batch file that utilizes appcmd.exe. In IIS 7.5 on 2008 r2 by default after provisioning a server the ASP.NET 4.0 isapi.dlls are restricted.  I got the following to work by using action :config instead of action :set.  I'd still rather pass the commands as an array instead of separate commands. I'll work on trying to accomplish that. 

iis_config "/section:isapicgiRestriction /[path='C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\aspnet_isapi.dll'].allowed:True" do
        action :config
    end

iis_config "/section:isapicgiRestriction /[path='C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\aspnet_isapi.dll'].allowed:True" do
        action :config
    end

https://github.com/chef-cookbooks/iis

iis_config
Runs a config command on your IIS instance.

Actions
:set - Edit configuration section (appcmd set config)
:clear - Clear the section configuration (appcmd clear config)
:config - [ DEPRECATED ] use :set instead

# Loads an array of commands from the node
cfg_cmds = node['iis']['cfg_cmd']
cfg_cmds.each do |cmd|
    iis_config "#{cmd}" do
        action :set
    end
end

That is where I saw the action :set and it stated :config was deprecated.

**Comment by EasyAsABC123** [comment]
Absolutely array passing definitely works.

In the meantime what happens if you do:

```ruby
iis_config "/section:isapicgiRestriction /[path='C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\aspnet_isapi.dll'].allowed:True" do
        action :set
    end

iis_config "/section:isapicgiRestriction /[path='C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\aspnet_isapi.dll'].allowed:True" do
        action :set
    end
```

**Comment by bradwilliamson** [comment]
Chef-Client on the node produces this error 

`2016-05-05T10:48:50-05:00] FATAL: Chef::Exceptions::ValidationFailed: Option action must be equal to one of: nothing, config!  You passed :set.`

The` :action :config `seems to do the job.

**Comment by bradwilliamson** [comment]
Here is the stacktrace output

`Generated at 2016-05-05 10:48:50 -0500
Chef::Exceptions::ValidationFailed: Option action must be equal to one of: nothing, config!  You passed :set.
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/mixin/params_validate.rb:170:in `_pv_equal_to'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/mixin/params_validate.rb:106:in `block (2 levels) in validate'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/mixin/params_validate.rb:103:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/mixin/params_validate.rb:103:in `block in validate'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/mixin/params_validate.rb:93:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/mixin/params_validate.rb:93:in `validate'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource.rb:174:in `block in action'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource.rb:173:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource.rb:173:in `action'
C:/chef/cache/cookbooks/jms192/recipes/jmsinstall2.rb:158:in `block in from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource_builder.rb:76:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource_builder.rb:76:in `build'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/dsl/declare_resource.rb:102:in `build_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/dsl/declare_resource.rb:62:in `declare_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/dsl/resources.rb:40:in `iis_config'
C:/chef/cache/cookbooks/jms192/recipes/jmsinstall2.rb:157:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/cookbook_version.rb:233:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/run_context.rb:354:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/run_context.rb:176:in `load'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/client.rb:508:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/client.rb:278:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application.rb:267:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application.rb:243:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application.rb:226:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application/client.rb:456:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application/client.rb:443:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application/client.rb:442:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application/client.rb:442:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application/client.rb:426:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application.rb:58:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:61:in `load'
C:/opscode/chef/bin/chef-client:61:in `<main>'`

**Comment by EasyAsABC123** [comment]
It looks like you are running an older version of the iis cookbook, on the chef server can you verify it is 4.1.8?

I'll spin up a test windows server 2008r2 after work today to test this if you are sure you have 4.1.8

**Comment by bradwilliamson** [comment]
The action on :set appears to be working now. I downloaded the cookbook on the 22nd of April. Appears it wasn't at 4.1.8 & somehow was at 4.1.1 but the readme stated 4.1.7.  I just went in and removed it entirely & downloaded 4.1.8. The below code is working for me fine now. 
```

#Allows/Enables ASP.NET 4x ISAPI filters. Will eventually pass both commands through array
iis_config "/section:isapicgiRestriction /[path='C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\aspnet_isapi.dll'].allowed:True" do
        action :set
    end

#See Above
iis_config "/section:isapicgiRestriction /[path='C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\aspnet_isapi.dll'].allowed:True" do
        action :set
    end

```

**Comment by EasyAsABC123** [comment]
awesome! does the array loop method still fail?

**Comment by bradwilliamson** [comment]
I will attempt to get it work after 3:30 PM CST today. Stuck in meetings until then.

**Comment by EasyAsABC123** [comment]
Thanks, let me know whenever and i'll try to look into any issue you find.

**Comment by bradwilliamson** [comment]
I got it to work with just one command inside the array. When I put two commands in the array I got the following error. 

`---- Begin output of C:\Windows\System32\inetsrv\appcmd.exe set config /section:isapicgiRestriction /[path='C:\Windows\M
icrosoft.NET\Framework64\v4.0.30319\aspnet_isapi.dll'] ----
STDOUT: ERROR ( message:The attribute "[path='C:\Windows\Microsoft.NET\Framework64\v4.0.30319\aspnet_isapi.dll']" is not
 supported in the current command usage. )
STDERR:
---- End output of C:\Windows\System32\inetsrv\appcmd.exe set config /section:isapicgiRestriction /[path='C:\Windows\Mic
rosoft.NET\Framework64\v4.0.30319\aspnet_isapi.dll'] ----
Ran C:\Windows\System32\inetsrv\appcmd.exe set config /section:isapicgiRestriction /[path='C:\Windows\Microsoft.NET\Fram
ework64\v4.0.30319\aspnet_isapi.dll'] returned 87`

Here is the code 

`# Ruby Array of commmands passed to iis_config which passes to appcmd.exe
iiscfg_cmds = ["/section:isapicgiRestriction /[path='C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\aspnet_isapi.dll'].allowed:True", "/section:isapicgiRestriction /[path='C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\aspnet_isapi.dll']"] 
iiscfg_cmds.each do |cmd|
    iis_config "#{cmd}" do
        action :set
    end
end`

**Comment by EasyAsABC123** [comment]
I can't even get these commands to run, can you please provide the information you are doing to setup iis to allow for the above commands I only get:

```
ERROR ( message:Cannot find requested collection element. )
```

Closing until more detail provided
