### ISSUE TITLE
default recipe fails on 2012r2

### ISSUE THREAD

**Issue by vinyar** [chef-cookbooks/iis#280]
### Cookbook version
4.1.8

### Chef-client version
12.10.24

### Platform Details
2012r2

### Scenario:
get base line IIS working (for free)

### Steps to Reproduce:
add iis:default to runlist

### Expected Result:
some basic iis functionality gets installed.

### Actual Result:
(0/43 features get installed)
The feature itself gets the checkbox, but none of the sub-features are added.
Resulting in service w3svc failure with 'no service found error'

Solution would be to add a default set of roles/features for 2012. Equivalent to clicking Web Server checkbox in UI:
IIS, Web management console, iis service, etc..
(it's an easy PR, sorry I don't have time right now)

**Comment by vinyar** [comment]
```
Recipe: iis::default
         * windows_feature[IIS-WebServerRole] action install

         * windows_service[iis] action enable

           ================================================================================
           Error executing action `enable` on resource 'windows_service[iis]'
           ================================================================================

           SystemCallError
           ---------------
           The specified service does not exist as an installed service. - OpenService: The specified service does not exist as an installed service.

           Resource Declaration:
           ---------------------
           # In C:\Users\vagrant\AppData\Local\Temp\kitchen\cookbooks\iis\recipes\default.rb

            32: service 'iis' do
            33:   service_name 'W3SVC'
            34:   action [:enable, :start]
            35: end
```

**Comment by vinyar** [comment]
eh.... ok. I get it. It's due to mwrocks box not having any of the features on the box.
Maybe it's worth the effort to add a dism /do_i_have_any_files_locally as a guard (dism /scanhealth or something like get-windowsfeature | where webserver -not removed)

**Comment by EasyAsABC123** [comment]
Definitely sounds like an idea

**Comment by sasideveloper** [comment]
Vinyar,
How did you overcome this problem.

**Comment by EasyAsABC123** [comment]
@sasideveloper he either logged into the box and installed the feature or he added this to the default recipe:

```ruby
powershell_script 'Install IIS' do
  code <<-EOH
  Import-Module ServerManager
  Add-WindowsFeature Web-Server
  EOH
  guard_interpreter :powershell_script
  not_if "Import-Module ServerManager; (Get-WindowsFeature -Name Web-Server).Installed"
end
```

**Comment by vinyar** [comment]
@sasideveloper truth be told, I had packer files from when I messed around with it, so I used a different 2012 image I cooked up a few months ago.

Packer takes an hour at most to learn, but another 3 to download the mega massive 2012r2 ISO from msft.
https://github.com/boxcutter/windows

@EasyAsABC123 I was thinking something like `(Get-WindowsFeature -Name Web-Server) -ne 'removed'`

**Comment by EasyAsABC123** [comment]
@vinyar feel free to add a pull request

**Comment by sasideveloper** [comment]
Problem for me is service is getting installed but it is not recognized by system until i restart the system. Henceforth my next logic which tries appcmd are failing. Whereas when i run "Add-WindowsFeature Web-Server" in powershell directly, service is getting recognized without restart.

**Comment by EasyAsABC123** [comment]
@sasideveloper please provide this as a new issue with the windows server version and any relevant recipes as this issue is closed.  Adding Powershell functionality is possible, simply submit a pull request.  Please note it will need to check that powershell is available and fail to current method otherwise.
