### ISSUE TITLE
IIS Service is not recognized after installation

### ISSUE THREAD

**Issue by sasideveloper** [chef-cookbooks/iis#281]
### Cookbook version
4.1.8

### Chef-client version
12.5.1

### Platform Details
Windows Server 2012R2 in AWS

### Scenario:
I am trying to run default.rb on new windows 2012 machine

### Steps to Reproduce:
create new machine and run IIS::default.rb 

### Expected Result:
Successfully completed iis installation and start IIS Service.

### Actual Result:
Converging 71 resources
Recipe: iis::default
  * windows_feature[IIS-WebServer] action install

  * windows_feature[IIS-WebServerRole] action install (up to date)
  * windows_service[iis] action enable

    ============================================================================
====
    Error executing action `enable` on resource 'windows_service[iis]'
    ============================================================================
====

    SystemCallError
    ---------------
    The specified service does not exist as an installed service. - OpenService:
 The specified service does not exist as an installed service.

    Resource Declaration:
    ---------------------
    # In C:/Users/test/.chef/local-mode-cache/cache/cookbooks/iis/recip
es/default.rb

     32: service 'iis' do
     33:   service_name 'W3SVC'
     34:   action [:enable, :start]
     35: end

**Comment by EasyAsABC123** [comment]
Hello @sasideveloper this is likely the same #280
Please verify that the server has get-windowsfeature iis even installed.
