### ISSUE TITLE
iis_config editing into Framework instead of Framework64

### ISSUE THREAD

**Issue by pratikpotdar** [chef-cookbooks/iis#282]
When running the same command using CMD it sets the value correctly under Framework64/Config/web.config for /commit:WEBROOT

When done through iis_config, it changes in Framework/Config/web.config

Am I missing something? Is there an option to point it to the right web.config ?

### Cookbook version
4.1.8

### Chef-client version
12.5.1

### Platform Details
AWS - Windows server 2012R2

### Scenario:
Ensure Cookies Are Set With HttpOnly Attribute

### Steps to Reproduce:
```
iis_config "/commit:WEBROOT /section:system.web/httpCookies /httpOnlyCookies:true" do
  action :set
ens
```

### Expected Result:
To edit web.config file in C:\Windows\Microsoft.NET\ **Framework64** \v4.0.30319\Config

### Actual Result:
Editing web.config in : C:\Windows\Microsoft.NET\ **Framework** \v4.0.30319\Config

**Comment by EasyAsABC123** [comment]
What command are you running and from which appcmd?
```
C:\windows\system32\inetsrv\appcmd
C:\windows\SysWow64\inetsrv\appcmd
```
Command?
```
appcmd set config /commit:WEBROOT /section:system.web/httpCookies /httpOnlyCookies:true
```

**Comment by pratikpotdar** [comment]
I am running it from this appcmd through CMD: C:\windows\system32\inetsrv\appcmd

which makes entry in Framework64

And the command that is used:
appcmd.exe set config /commit:WEBROOT /section:system.web/httpCookies /httpOnlyCookies:true

**Comment by EasyAsABC123** [comment]
Running the same command on my x64 box doesn't make an entry into the framework64 file.  Can you validate resetting the box and then seeing if the file is touched with the appcmd only without inetsrv.

Just want to make sure it is all executing, otherwise the issue would be somewhere with chef running as a 32 bit program.  I don't think that should cause any issue I can write up a quick .rb file that will do the same thing chef is running.  However, literally it is just executing the same command you just posted.

Justin Schuhmann

**Comment by pratikpotdar** [comment]
@EasyAsABC123 Tried it. `C:\\windows\\system32\\inetsrv\\appcmd.exe set config /commit:WEBROOT /section:system.web/httpCookies /httpOnlyCookies:true` 
This still makes an entry in Framework64
From recipe, it still goes to Framework

**Comment by EasyAsABC123** [comment]
@pratikpotdar sounds good, thanks for validating.

Whenever I get a moment I'll try to write up that ruby file that executes the same way the recipe does.  The reason for this is to see if it is because of ruby or because of chef.  As the command above is the literal command that this cookbook would do given what you have posted

**Comment by EasyAsABC123** [comment]
@pratikpotdar just ran the following:
```
$ kitchen test
```

This runs the following recipes
```
      - recipe[iis::default]
      - recipe[iis_test::default]
```

recipe[iis_test::default]
```ruby
#
# Cookbook Name:: iis_test
# Recipe:: default
# tests the iis cookbook

iis_config "/commit:WEBROOT /section:system.web/httpCookies /httpOnlyCookies:true" do
  action :set
end

iis_pool "DB Necromancer" do
  runtime_version "4.5"
  pipeline_mode :Integrated
  action [:add, :start]
end

# creates a new app pool
iis_pool 'myAppPool_v1_1' do
  runtime_version "2.0"
  pipeline_mode :Classic
  action [:add, :config]
end

# stop and delete the default site
iis_site 'Default Web Site' do
  action [:stop, :delete]
end

directory "#{node['iis']['docroot']}testfu" do
  recursive true
end

directory "#{node['iis']['docroot']}testfu/v1_1" do
  recursive true
end

# creates a new app pool
iis_pool 'poal_Testwebsite' do
  runtime_version "2.0"
  pipeline_mode :Classic
  action :add
end

iis_site 'poal_Testwebsite' do
  protocol :http
  port 90
  path "#{node['iis']['docroot']}testfu/v1_1"
  host_header ""
  application_pool "poal_Testwebsite"
  action [:add,:config]
end

# create and start a new site that maps to
# the physical location C:\inetpub\wwwroot\testfu
iis_site 'Testfu Site' do
  protocol :http
  port 80
  application_pool "DB Necromancer"
  path "#{node['iis']['docroot']}testfu"
  action [:add,:start]
end

# create and start a new site that maps to
# the physical C:\inetpub\wwwroot\testfu
# also adds bindings to http and https
# binding http to the ip address 10.12.0.136,
# the port 80, and the host header www.domain.com
# also binding https to any ip address,
# the port 443, and the host header www.domain.com
iis_site 'FooBar Site' do
  application_pool "DB Necromancer"
  bindings 'http/10.12.0.136:80:www.domain.com,https/*:443:www.domain.com'
  path "#{node['iis']['docroot']}testfu"
  action [:add,:start]
end

# creates a new app
iis_app "FooBar Site" do
  path "/v1_1"
  application_pool "myAppPool_v1_1"
  physical_path "#{node['iis']['docroot']}testfu/v1_1"
  enabled_protocols "http,net.pipe"
  action :add
end

directory 'C:\wwwroot\shared\test' do
  recursive true
end

directory 'C:\wwwroot\shared\test' do
  recursive true
end

# add a virtual directory to default application
iis_vdir 'FooBar Site/' do
  action :add
  path '/Content/Test'
  physical_path 'C:\wwwroot\shared\test'
end

# add a virtual directory to an application under a site
iis_vdir 'FooBar Site/v1_1' do
  action :add
  path '/Content/Test'
  physical_path 'C:\wwwroot\shared\test'
end
```

As you can see
```ruby

iis_config "/commit:WEBROOT /section:system.web/httpCookies /httpOnlyCookies:true" do
  action :set
end
```

I then checked the file C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config, which contains:
```
<httpCookies httpOnlyCookies="true" />
```

**Comment by EasyAsABC123** [comment]
Closing issue, feel free to re-open.  I tested this on the same system you have locally with test-kitchen and it doesn't behave as described.

Please run a 
```
chef-client -z -l debug > C:\debug_file.txt 
```
and submit it to this issue reopening the issue as well.

thanks

**Comment by burnzy** [comment]
@pratikpotdar @EasyAsABC123 I'm experiencing that same issue - specifically when trying to update the machine.config. It seems that it always updates the Framework config instead of the Framework64 when running chef. But manually running appcmd will update the Framework64 config. How did you resolve this issue earlier?

**Comment by EasyAsABC123** [comment]
@burnzy can you please run the above command to give me the debug log?

**Comment by burnzy** [comment]
@EasyAsABC123 I'm running with test-kitchen + vagrant does that make a difference?

**Comment by burnzy** [comment]
@EasyAsABC123 https://gist.github.com/burnzy/a3c73f762e3a7420350cafc35dd190c7

**Comment by pratikpotdar** [comment]
@EasyAsABC123 Sorry, but I had some issues with my email account and might have missed the notification emails. It's OK if you closed the issue. Maybe you can re-open it with the output that burnzy  has submitted. I do not have access to the windows environment anymore and wouldn't be able to test it. :(

@burnzy I simply put the appcmd command in an execute block. That seemed to work. Had to deliver the cookbook quickly for a roll out, hence didn't really spend a lot of time debugging the issue.

**Comment by EasyAsABC123** [comment]
@burnzy the file you posted shows a node with a runlist of nothing.  I am guessing you didn't make a [machine name].json file before running the above command to get the -verbose log.   Because of this the above only shows information about the server but not any details on what the server is doing.

Try again if you can but you will need to make a node file

Example file (don't use this exactly this is just an example)
```
{
  "mysql": {
     "server_root_password": "password",
     "server_repl_password": "password",
     "server_debian_password": "password"
  },
  "apache": {
    "listen_ports": [
      "80", "8080"
    ]
  },
  "run_list": [
    "recipe[apt]",
    "recipe[apache2]",
    "recipe[apache2::mod_rewrite]",
    "recipe[apache2::mod_headers]",
    "recipe[apache2::mod_deflate]",
    "recipe[perl]",
    "recipe[mysql::client]",
    "recipe[mysql::server]",
    "recipe[koha::requirements]",
    "recipe[koha]"
  ]
}
```

**Comment by burnzy** [comment]
@EasyAsABC123 Okay, I've re-run, and updated the gist: https://gist.github.com/burnzy/a3c73f762e3a7420350cafc35dd190c7

**Comment by EasyAsABC123** [comment]
@burnzy I should apologize, I need the above ran on a machine that isn't configured so that IIS commands run.  The above log shows nothing because everything is (up-to-date).  Sorry about that, let me look at the logging to make sure that it will log the files that it is writing to as well
