### ISSUE TITLE
Add deprecation warnings for iis_config in 4.2

### ISSUE THREAD

**Issue by spuder** [chef-cookbooks/iis#284]
The `iis_config` resources in 4.2 will no longer support `:config`. 

Users will need to change every instance of `:config` to `:set`

I recommend adding a deprecation warning to 4.1 IIS cookbook, so users aren't caught off guard updating to 4.2. I had nearly a dozen references to the old syntax and had to find all of them. 

```ruby
  Chef::Exceptions::ValidationFailed
  ----------------------------------
  Option action must be equal to one of: nothing, clear, set!  You passed :config.

  Platform:
  ---------
  i386-mingw32
```

Here is an example of adding a deprecation warning, taken from the yum cookbook

https://github.com/chef-cookbooks/yum/blob/master/providers/repository.rb#L39-L44
```ruby
  if new_resource.clean_headers
    Chef::Log.warn <<-eos
      Use of `clean_headers` in resource yum[#{new_resource.repositoryid}] is now deprecated and will be removed in a future release.
      `clean_metadata` should be used instead
    eos
  end
```

**Comment by EasyAsABC123** [comment]
@spuder do you mean add a warning to 4.1.8? 

it is removed completely in 4.2, and because of the load resource it can't really be used unless I simply keep it doing set and not tell anyone.

**Comment by spuder** [comment]
@EasyAsABC123 Yes, my thought is to release a 4.1.9 cookbook that warns what changes in the iis_config in version 4.2.0. I had to change a significant amount of code to get 4.2 to work. It would be nice for others to get a heads up.

**Comment by EasyAsABC123** [comment]
deployed to supermarket, agree that hopefully his helps people migrate to
4.2.0.

I think the `:clear` issue will be resolved this week if i get time to work
on it.  i'm out of town monday and tuesday at the office...so i won't be
able to work on it until after that
