### ISSUE TITLE
Error 50: Adding IIS Components (features) on server 2008 r2.

### ISSUE THREAD

**Issue by Yvangelist01** [chef-cookbooks/iis#287]
### Cookbook version
4.1.6

### Chef-client version
12.8.1

### Platform Details
Windows Server 2008 R2

### Scenario:
Error 50: Adding IIS Components (features) on server 2008 r2.

### Steps to Reproduce:
In your test cookbook add the following components on a server 2008 r2.
```ruby
node.override['iis']['components'] = ['IIS-WebServer', 'WAS-WindowsActivationService', 'WAS-ProcessModel']
```

then just

```ruby
include_recipe 'iis'
```

### Expected Result:
Should be successful 

### Actual Result:
I get Error 50 DISM. 
Basically it tries to add IIS-WebServer features from your additional components but fails because the IIS-WebServerRole is not installed.

So either changes the all attribute  in default windows_feature to support older than server 2008 r2
or just change the order of the array of the feature loop to put default first then the additional components:
```ruby
iis:default.rb
default = Opscode::IIS::Helper.older_than_windows2008r2? ? 'Web-Server' : 'IIS-WebServerRole'


(node['iis']['components'] + [default]).each do |feature|
  windows_feature feature do
    action :install
    all !Opscode::IIS::Helper.older_than_windows2012?
    source node['iis']['source'] unless node['iis']['source'].nil?
  end
end

service 'iis' do
  service_name 'W3SVC'
  action [:enable, :start]
end
```

**Comment by EasyAsABC123** [comment]
Please submit a pull request with the fix, thanks

**Comment by Yvangelist01** [comment]
Yes I tough of it. But wouldn't the server role installation be triggered twice ? 
I mean once from the additional components and then another time with the 'default'.

**Comment by EasyAsABC123** [comment]
I think I found the issue, I committed a change to master, please pull it down and confirm.  thanks

**Comment by EasyAsABC123** [comment]
@Yvangelist01 please verify whenever possible.  Closing issue for now
