### ISSUE TITLE
mod_management recipe fails to install due to dependent features not installed

### ISSUE THREAD

**Issue by roberto-mardeni** [chef-cookbooks/iis#293]
### Cookbook version
5.0.0

### Chef-client version
12.13.37

### Platform Details
Windows 2012 R2

### Scenario:
Configure IIS with the management feature only

### Steps to Reproduce:
Write a cookbook with:
include_recipe 'iis'
include_recipe 'iid::mod_management'

### Expected Result:
Features should be installed without any errors

### Actual Result:
The following error occurs:
       [2016-09-21T06:41:10-07:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: windows_feature[IIS-ManagementService] (iis::mod_management line 30) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 42, 127, 3010], but received '50'
       ---- Begin output of C:\Windows\system32\dism.exe /online /enable-feature /featurename:IIS-ManagementService /norestart   ----
       STDOUT: Deployment Image Servicing and Management tool
       Version: 6.3.9600.16384

       Image Version: 6.3.9600.16384

       Enabling feature(s)

       Error: 50

       The operation is complete but IIS-ManagementService feature was not enabled.
       A required parent feature may not be enabled. You can use the /enable-feature /all option to automatically enable each parent feature from the following list. If the parent feature(s) are already enabled, refer to the log file for further diagnostics.
       NetFx4Extended-ASPNET45

**Comment by smurawski** [comment]
Thanks for the PR, it just needs a quick tweak to make it support 2008 R2, as well as 2012/2012 R2.

**Comment by iennae** [comment]
Fixed with version 5.0.1.
