### ISSUE TITLE
iis_version is not evaluated properly on if statement

### ISSUE THREAD

**Issue by mitchflores** [chef-cookbooks/iis#308]
### Cookbook version
5.0.5

### Chef-client version
12.19.36

### Platform Details
Windows server 2016

### Scenario:
[What you are trying to achieve and you can't?]

### Steps to Reproduce:
Add/Config an application pool using iis_pool Resource/Provider and set pool_identity to :NetworkService to :SpecificUser.

### Expected Result:
app pool identity should be updated.

### Actual Result:
app pool identity is set to ApplicationPoolIdentity by the default.

Note: Seems like on the if statement condition, version number in string type was not evaluated properly, I tried changing the type from string to float then works as expected. I suppose changing the return value type of iis_version def in helper.rb at line 99 from string to float can resolve this issue, and also to update the if statement conditions on pool.rb to change '7.0' to 7.0

I propose something like this:
helper.rb
from
`@iis_version = version_string`
to
`@iis_version = version_string.to_f`
and on pool.rb
from
`if iis_version > '7.0'`
to
`if iis_version > 7.0`

**Comment by EasyAsABC123** [comment]
let me know if this resolves it for you.

**Comment by mitchflores** [comment]
Hi @EasyAsABC123 thank you very much for the update, it resolves my issue.
