### ISSUE TITLE
iis service in default recipe creates error on knifing new server

### ISSUE THREAD

**Issue by Stromweld** [chef-cookbooks/iis#315]
### Cookbook version
5.0.8
### Chef-client version
12.19.36

### Platform Details
Windows 2012 R2 on AWS cloud

### Scenario:
Knife a new windows server with IIS cookbook and windows 3.0.0 cookbook

### Steps to Reproduce:
install windows 3.0.0 and iis 5.0.8 cookbooks
knife new server with iis::default recipe.

### Expected Result:
new server created with iis installed and running

### Actual Result:
Below is copy of the error output when knifing a new server. After reboot of the server and running chef-client it completes normally. 

172.21.16.68 [2017-03-20T14:13:23-05:00] INFO: Processing windows_service[iis] action enable (iis::default line 32)
172.21.16.68 
172.21.16.68 
172.21.16.68 ================================================================================
172.21.16.68 Error executing action `enable` on resource 'windows_service[iis]'
172.21.16.68 ================================================================================
172.21.16.68 
172.21.16.68 SystemCallError
172.21.16.68 ---------------
172.21.16.68 The specified service does not exist as an installed service. - OpenService: The specified service does not exist as an installed service.
172.21.16.68 
172.21.16.68 Resource Declaration:
172.21.16.68 ---------------------
172.21.16.68 # In c:/chef/cache/cookbooks/iis/recipes/default.rb
172.21.16.68 
172.21.16.68  32: service 'iis' do
172.21.16.68  33:   service_name 'W3SVC'
172.21.16.68  34:   action [:enable, :start]
172.21.16.68  35: end
172.21.16.68 
172.21.16.68 Compiled Resource:
172.21.16.68 ------------------
172.21.16.68 # Declared in c:/chef/cache/cookbooks/iis/recipes/default.rb:32:in `from_file'
172.21.16.68 
172.21.16.68 windows_service("iis") do
172.21.16.68   action [:enable, :start]
172.21.16.68   supports {:restart=>nil, :reload=>nil, :status=>nil}
172.21.16.68   retries 0
172.21.16.68   retry_delay 2
172.21.16.68   default_guard_interpreter :default
172.21.16.68   service_name "W3SVC"
172.21.16.68   enabled nil
172.21.16.68   running nil
172.21.16.68   masked nil
172.21.16.68   pattern "iis"
172.21.16.68   startup_type :automatic
172.21.16.68   declared_type :service
172.21.16.68   cookbook_name "iis"
172.21.16.68   recipe_name "default"
172.21.16.68 end
172.21.16.68 
172.21.16.68 Platform:
172.21.16.68 ---------
172.21.16.68 x64-mingw32
172.21.16.68 
172.21.16.68
172.21.16.68 [2017-03-20T14:13:23-05:00] INFO: Running queued delayed notifications before re-raising exception
172.21.16.68 [2017-03-20T14:13:26-05:00] ERROR: Running exception handlers
172.21.16.68 [2017-03-20T14:13:26-05:00] ERROR: Exception handlers complete
172.21.16.68 [2017-03-20T14:13:26-05:00] INFO: Sending resource update report (run-id: 1348a0f8-b55f-4469-b0d4-8517e3debabc)
172.21.16.68 [2017-03-20T14:13:26-05:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
172.21.16.68 [2017-03-20T14:13:26-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
172.21.16.68 [2017-03-20T14:13:26-05:00] FATAL: SystemCallError: windows_service[iis] (iis::default line 32) had an error: SystemCallError: The specified service does not exist as an installed service. - OpenService: The specified service does not exist as an installed service.
ERROR: Failed to execute command on 172.21.16.68 return code 1
ERROR: Bootstrap command returned 1

**Comment by EasyAsABC123** [comment]
Refer to:
#281 
#203 
#280 

Thanks, if issue persists after reading those feel free to reopen

**Comment by Stromweld** [comment]
I was using this cookbook in the past but now windows 3.0.0 came out and they changed some of things and now knifing a new server is failing. I'm not sure what change that caused the breakage here.

**Comment by EasyAsABC123** [comment]
please read this issue: https://github.com/chef-cookbooks/iis/issues/280

it describes exactly what you are describing...you have changed your image, the new image doesn't contain the files so you need to point to the installation source via the `default['iis']['source'] = nil` attribute

**Comment by Stromweld** [comment]
it installs everything fine, but it looks like windows 3.0.0 now relies on chef-client built in windows_feature which if no provider is specified defaults to dism install instead of powershell. Below is snippets from release notes.

windows_feature

BREAKING CHANGE - Version 3.0.0

There are three methods for the windows_feature which map into Microsoft's three major tools for managing roles/features: Deployment Image Servicing and Management (DISM), Servermanagercmd (The CLI for Server Manager), and PowerShell. As Servermanagercmd is deprecated, Chef will set the default method to :windows_feature_dism if dism.exe is present on the system being configured. The default method will fall back to :windows_feature_servermanagercmd, and then :windows_feature_powershell.

For Dism:

dism /online /Get-Features
For ServerManagerCmd:

servermanagercmd -query
For PowerShell:

get-windowsfeature

Properties

install_method - Symbol. Optional. REPLACEMENT FOR THE PREVIOUS PROVIDER OPTION If not supplied, Chef will determine which method to use (in the order of :windows_feature_dism, :windows_feature_servercmd, :windows_feature_powershell)

**Comment by EasyAsABC123** [comment]
can you run the commands provided and see which one has iis functionality?
For Dism:
```
dism /online /Get-Features
```

For ServerManagerCmd:
```
servermanagercmd -query
```

For PowerShell:
```
get-windowsfeature
```

**Comment by Stromweld** [comment]
Dism:
`Feature Name : IIS-WebServerRole
State : Enabled`

PowerShell:
`Web-Server         Installed`

**Comment by EasyAsABC123** [comment]
that looks like Dism installed it, so did powershell? did you uninstall the feature between?

**Comment by Stromweld** [comment]
no just installed with iis cookbook and rebooted the server.

**Comment by EasyAsABC123** [comment]
so it just worked? or did you change something, if you did feel free to submit a pull request

**Comment by Stromweld** [comment]
I'm confused, so I tested knifing a server with runlist recipe[iis]. That worked and full converged on first chef run. Then I tested our wrapper cookbook again in the run list which includes ms_dotnet cookbook to install .net 4.6.2 then run iis::default then some of our other stuff. with the wrapper cookbook it fails with the service error.

**Comment by EasyAsABC123** [comment]
not sure, try turning on --verbose and looking through the logs...sounds like something is wrong with the versioning between the wrapper cookbook and this cookbook, but obviously i don't know i'm throwing knifes in the dark

**Comment by Stromweld** [comment]
I'm going to try another test where I moved ms_dotnet to be the last cookbook ran in the wrapper and first one is iis::defualt.

**Comment by EasyAsABC123** [comment]
that seems like a good plan, it might be that a restart is required between the .net install and iis

**Comment by Stromweld** [comment]
Sure enough that was it. Can't remember if I tested knifing a new server after adding the ms_dotnet cookbook or not. I could of swore I did test it before windows 3.0.0 came out. Thanks for the help. 

So for clarity if others find this in a search. ms_dotnet install of .net 4.6.2 must come after IIS cookbooks install of IIS-WebServerRole or the iis::default recipe.

**Comment by davidalpert** [comment]
thank you for this thread; I was going to log a new issue but found this one (thanks github suggestions!) and updated my own cookbook to do this after installing the .NET Framework 4.7.1 resource:
```
  reboot 'only if needed' do
    action :reboot_now
    reason 'Cannot continue Chef run without a reboot.'
    only_if { node['dotnet']['install']['reboot_if_required'] && reboot_pending? }
  end
```
and now the converge succeeds with an immediate reboot the first time after installing the .NET Framework 4.7.1 package, then the following converge completes `iis::default` fine as expected on the first try.
