### ISSUE TITLE
Uninitialized constant Chef::Resource::IisSite

### ISSUE THREAD

**Issue by stonesbg** [chef-cookbooks/iis#318]
### Cookbook version
windows => 3.0.3
iis => 5.1.0

### Chef-client version
Chef Client 12.19.36

### Platform Details
Windows Server 2012 R2

### Scenario:
i am trying to install a new web site using the iis_site resource

### Steps to Reproduce:
1. Create a cookbook with a resource for iis_site
2. Execute chef-client

### Expected Result:
Web site is created

### Actual Result:
I am getting the error:

NameError
---------
uninitialized constant Chef::Resource::IisSite

**Comment by EasyAsABC123** [comment]
@stonesbg i'm also experiencing this...i'm assuming it is something that is incompatible in the cookbook and needs to be updated.

@tas50 anything that i should change here? i'm getting the same thing in test-kitchen when testing

**Comment by iennae** [comment]
The issue here is that we need to refactor the resources to new custom resource. We're working on getting this resolved.

**Comment by krm1** [comment]
I'm getting:
`FATAL: NameError: uninitialized constant Chef::Recipe::Opscode`

Is this the same error cause?

**Comment by EasyAsABC123** [comment]
@krm1 are you getting that specifically to this cookbook or just in general?

I don't know if there is a `Chef::Recipe::Opscode` there used to be a `Opscode::Recipe` now there is a [`Chef::Recipe`](http://www.rubydoc.info/github/opscode/chef/Chef/Recipe)

@iennae this one is all you.

**Comment by krm1** [comment]
@EasyAsABC123 Sorry, please ignore my comment, I had used it wrong.

**Comment by meganuke19** [comment]
I have received the same error

### Cookbook version
windows => 3.0.5
iis => 6.0.1

### Chef-client version
13.0.113

### Platform Details
Windows Server 2012 R2

```
   * windows_service[iis] action start (up to date)
 Recipe: webapp-deploy::default
   * directory[C:\inetpub\wwwroot/target] action create (up to date)
   * iis_site[Target Site] action add

     ================================================================================
     Error executing action `add` on resource 'iis_site[Target Site]'
     ================================================================================
     NameError
     ---------
     uninitialized constant Chef::Resource::IisSite
     Cookbook Trace:
     ---------------
     C:/chef/cache/cookbooks/iis/providers/site.rb:103:in `load_current_resource'
     Resource Declaration:
     ---------------------
     # In C:/chef/cache/cookbooks/webapp-deploy/recipes/default.rb

      17: iis_site 'Target Site' do
      18:   protocol :http
      19:   port 80
      20:   path "#{node['iis']['docroot']}/target"
      21:   host_header "winwebapp.dev"
      22:   action [:add,:start]
      23: end
      24:
```
In my stacktrace.

**Comment by EasyAsABC123** [comment]
This issue is because of the custom resource requirements...iis_site hasn't been converted yet...sorry for closing the issue someone hijacked yours with something else and then said it was fixed...my bad

**Comment by EasyAsABC123** [comment]
This is resolved
