### ISSUE TITLE
uninitialized constant Chef::Resource::IisPool

### ISSUE THREAD

**Issue by thpert** [chef-cookbooks/iis#329]
### Cookbook version
6.2

### Chef-client version
13.0.118

### Platform Details
Windows 2008 R2

### Scenario:
Just trying to create an IIS app pool.

### Steps to Reproduce:
iis_pool 'TEST' do
  runtime_version '4.0'
  pipeline_mode :Integrated
  action [:add, :start]  
end

### Expected Result:
App Pool working like with chef-client 12.

### Actual Result:

NameError
---------
uninitialized constant Chef::Resource::IisPool

Resource Declaration:
---------------------
# In C:/chef/cache/cookbooks/webserver_dmz/recipes/default.rb

112: iis_pool 'TEST' do
113:   runtime_version '4.0'
114:   pipeline_mode :Integrated
115:   action [:add, :start]
116: end

**Comment by EasyAsABC123** [comment]
@thpert this is because iis_pool hasn't been updated to a custom resource.  This is in the process of completion now.

**Comment by EasyAsABC123** [comment]
@thpert resolved by #331
