### ISSUE TITLE
uninitialized constant Chef::Resource::IisSection

### ISSUE THREAD

**Issue by thpert** [chef-cookbooks/iis#330]
### Cookbook version
6.2.0

### Chef-client version
13.0.188

### Platform Details
Windows 2008 R2

### Scenario:
I am trying to execute this recipie:
include_recipe 'iis::mod_auth_windows'

### Steps to Reproduce:
Just include 'iis::mod_auth_windows' in a cookbook

### Expected Result:
Same behaviour as for chef-client 12

### Actual Result:
 NameError
 ---------
 uninitialized constant Chef::Resource::IisSection

 Resource Declaration:
 ---------------------
 # In C:/chef/cache/cookbooks/iis/recipes/mod_auth_windows.rb

  33: iis_section 'unlocks windows authentication control in web.config' do
  34:   section 'system.webServer/security/authentication/windowsAuthentication'
  35:   action :unlock
  36: end

**Comment by EasyAsABC123** [comment]
@thpert this is because iis_section isn't updated to the latest custom resource

**Comment by nhudacin** [comment]
Hit the same issue... Is there a workaround? I've tried downgrading as low as version 5.0.5 with the same result. Maybe this is a Chef-Client 13 issue? Trying to upgrade from 12 to 13.

**Comment by EasyAsABC123** [comment]
@nhudacin it is chef 13, this cookbook isn't fully functional on Chef 13.  

This is in progress:
#335
#331 
#327 
#325 
#322 

Currrently i'm rewriting this resource to be Chef 13 compatible, but i also have to write the inspec testing library.  I imagine this will be done tonight...feel free to put in some PRs:

Both:
`iis_root`
`iis_section`

are still not complete but they are re-written here: 
https://github.com/chef-cookbooks/iis/tree/enhancement-new_LWRP_style

This code isn't production ready and that is why we are re-writing and reviewing them one at a time with actual inspec tests

**Comment by thpert** [comment]
@EasyAsABC123: Any update on iis_section resource development?

**Comment by EasyAsABC123** [comment]
@thpert i uploaded the current development branch https://github.com/chef-cookbooks/iis/tree/enhancement-section_custom_resource but haven't finished the inspec resource yet

**Comment by EasyAsABC123** [comment]
@thpert latest update now is that the PR is open and being reviewed.  hopefully this can go in today so this bug can be resolved.  there are still 2 more resources that i need to update and write valid testing systems for so that bugs can be detected and resolved quickly in the future.

**Comment by EasyAsABC123** [comment]
resolved in #347
