### ISSUE TITLE
uninitialized constant Chef::Resource::IisRoot

### ISSUE THREAD

**Issue by EasyAsABC123** [chef-cookbooks/iis#333]
Cookbook version

Latest

Chef-client version

Latest

Platform Details

win2012r2

**Comment by thpert** [comment]
@EasyAsABC123 : I tested version 6.4.0 this morning, This version is fine for me (thanks a lot :-)), just iis_root is missing now...

**Comment by EasyAsABC123** [comment]
@thpert yeah [`iis_root`](https://github.com/chef-cookbooks/iis/issues/333) and [`iis_module`](https://github.com/chef-cookbooks/iis/issues/334)

**Comment by EasyAsABC123** [comment]
#351 resolves this
