### ISSUE TITLE
uninitialized constant Chef::Resource::IisModule

### ISSUE THREAD

**Issue by EasyAsABC123** [chef-cookbooks/iis#334]
Cookbook version

Latest

Chef-client version

Latest

Platform Details

win2012r2

**Comment by EasyAsABC123** [comment]
@spuder been able to test or update your company to the latest version?

**Comment by spuder** [comment]
No, we are still on 4.x. Haven't had time to do the refactoring for 5.x or 6.x

**Comment by EasyAsABC123** [comment]
@spuder bummer! let me know if there is anything i can do to help.

**Comment by EasyAsABC123** [comment]
Resolved by #372
