### ISSUE TITLE
Getting Error log is undefined method iis_site resource

### ISSUE THREAD

**Issue by stonesbg** [chef-cookbooks/iis#336]
### Cookbook version
6.2.0

### Chef-client version
13.0.118

### Platform Details
Windows Server 2012 R2

### Scenario:
I am using the iis_site resource to create

### Steps to Reproduce:
1. Add an iis_site that will create "Default Web Site" with bindings for http:80 and https:443
2. IIS feature is not enabled on server and therefore the appcmd.exe doesn't exist

### Expected Result:
iis website is created

### Actual Result:
NoMethodError
-------------
undefined method `log' for Custom resource iis_site from cookbook iis

**Comment by EasyAsABC123** [comment]
nice find, #337 only covers one of the resources when i think this issue is in all of them.  Also it doesn't pass the `Signed-off-by:` test.  I want to make sure that I don't just write this real quick and not let you get credit.  If you could fix the signed off i'll fix the other resources.
