### ISSUE TITLE
pool_identity - specific user - doesn't get configured. Instead picks up applicationpoolidentity

### ISSUE THREAD

**Issue by Chandra-Allaka** [chef-cookbooks/iis#340]
### Cookbook version
6.3.0

### Chef-client version
13.0.118

### Platform Details
Windows 2012 R2

### Scenario:
I am trying to create an IIS application pool with the identity type as a specific user and the specific user is a local admin on the server.

### Steps to Reproduce:
Using resources `iis_pool` as below
```ruby
iis_pool 'testapppool' do
  name v_test_apppool
  thirty_two_bit false
  runtime_version '4.0'
  pipeline_mode :Integrated
  start_mode :OnDemand
  identity_type :SpecificUser
  username "#{node['hostname']}\\vagrant"
  password 'vagrant'
  action :add
end
```

### Expected Result:
Application pool created with the identity selected as custom account and account mapped to the vagrant user credentials

### Actual Result:
Identity of the app pool is configured to ApplicationPoolIdentity

**Comment by EasyAsABC123** [comment]
thanks! i'll write this as a test and see what happens.

**Comment by EasyAsABC123** [comment]
This should be resolved in PR #341 
https://github.com/chef-cookbooks/iis/pull/341/commits/28363cc6a07f4aa6e8c2eee6afd7bf9cf434a982#diff-bcd2ef7b616cb6ea0c9517d52e314908
Is a test with your exact parameters...please note that 
`name v_test_apppool` was removed as this won't work unless v_test_apppool is defined somewhere above.

**Comment by Chandra-Allaka** [comment]
Thanks. Yes, v_test_apppool was defined outside somewhere else as a variable.

**Comment by EasyAsABC123** [comment]
@Chandra-Allaka no problem, minor bug right now with loading settings...fixing...

**Comment by EasyAsABC123** [comment]
@Chandra-Allaka resolved by #341

**Comment by Chandra-Allaka** [comment]
Thank you. Will this be in a new version of the cookbook 6.3.x?

**Comment by EasyAsABC123** [comment]
@Chandra-Allaka correct, v6.3.1 and above will have it
