### ISSUE TITLE
iis_pool :stop fails if app pool is already in stopped state

### ISSUE THREAD

**Issue by david-in-perth** [chef-cookbooks/iis#345]
### Cookbook version
6.3.1

### Chef-client version
Chef Client 13.0.118 (Kitchen 1.16.0)

### Platform Details
Windows Server 2012 R2

### Scenario:
Trying to ensure that an app pool is stopped, when it may or may not already be in the stopped state.

### Steps to Reproduce:
Run the `iis_pool` resource with `action :stop` on an app pool that is already in the stopped state. E.g.:

```
iis_pool 'DefaultAppPool' do
  action :stop
end
```

### Expected Result:
Nothing happens. The app pool is already in the desired state, so no further action is required.

More specifically, from inspection of the source code, I would expect the debug log output to show the following message:

> DefaultAppPool already stopped - nothing to do

### Actual Result:
```
           * iis_pool[DefaultAppPool] action stop

             ================================================================================
             Error executing action `stop` on resource 'iis_pool[DefaultAppPool]'
             ================================================================================

             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             Expected process to exit with [0], but received '1062'
             ---- Begin output of C:\Windows\System32\inetsrv\appcmd.exe stop apppool "DefaultAppPool" ----
             STDOUT: ERROR ( message:Application pool "DefaultAppPool" already stopped. )
```

**Comment by david-in-perth** [comment]
Looking at the diff between the old _providers\pool.rb_ and the new _resources\pool.rb_, it appears that #331 left out an `if running` check (or similar) on the `:stop` action.

The `:start` action has had an `unless new_resource.running` condition to replace the `if !@current_resource.running` clause, and the `:restart` action has an `if running` condition, but `:stop` has no such check.

The `:delete` action also seems to have lost its "if exists" check.

I haven't worked out what the `if current_resource.runtime_version` / `if !current_resource.runtime_version` checks do in _resources\pool.rb_ - could it have been a typo / copy-paste error?

**Comment by EasyAsABC123** [comment]
@david-in-perth as with all bugs it is of course unintentional, the reason for it would be difficult for me to recall...

should be resolved in #346 and the kitchen verify agrees

**Comment by EasyAsABC123** [comment]
resolved in #347

**Comment by david-in-perth** [comment]
Thanks @EasyAsABC123, especially for the quick turnaround!

Those `current_resource.runtime_version` checks still seem out of place to me - I suspect that they're causing `:start` to not work - but I'll try out 6.4.0 and submit another bug report if necessary.

**Comment by EasyAsABC123** [comment]
so `current_resource.runtime_version` is used to detect if the `iis_pool` exists or not as `exists` isn't preferred anymore.  This could be changed to state or any other property if runtime_version is the issue
