### ISSUE TITLE
iis_pool is not Idempotent 

### ISSUE THREAD

**Issue by omarrodriguez15** [chef-cookbooks/iis#354]
### Cookbook version
6.5.0

### Chef-client version
12.17.44
### Platform Details
Windows Server 2012 R2

### Scenario:
Converging my cookbook after an initial run throws and error saying it can't add a duplicate collection element.

### Steps to Reproduce:
Run a cookbook with the following twice. The second time is when I get the error
```
 iis_pool application_pool do
   runtime_version '4.0.30319'
   action [:add, :config, :start]
   thirty_two_bit true
   pipeline_mode :Integrated
   idle_timeout '00:00:00'
   identity_type :ApplicationPoolIdentity 
   load_user_profile false
 end
```

### Expected Result:
For it to converge more than once without failing

### Actual Result:
Fails on the second run with the following error.
```
         * iis_pool[My App Pool] action add

           ================================================================================
           Error executing action `add` on resource 'iis_pool[My App Pool]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '183'
           ---- Begin output of C:\Windows\System32\inetsrv\appcmd.exe add apppool /name:"My App Pool" /managedRuntimeVersion:v4.0.30319 /managedPipel
ineMode:Integrated /commit:\"MACHINE/WEBROOT/APPHOST\" ----
           STDOUT: ERROR ( message:Failed to add duplicate collection element "My App Pool". )
           STDERR:
           ---- End output of C:\Windows\System32\inetsrv\appcmd.exe add apppool /name:"My App Pool" /managedRuntimeVersion:v4.0.30319 /managedPipelin
eMode:Integrated /commit:\"MACHINE/WEBROOT/APPHOST\" ----
           Ran C:\Windows\System32\inetsrv\appcmd.exe add apppool /name:"My App Pool" /managedRuntimeVersion:v4.0.30319 /managedPipelineMode:Integrate
d /commit:\"MACHINE/WEBROOT/APPHOST\" returned 183

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/my/recipes/default.rb

            59: iis_pool application_pool do
            60:   runtime_version '4.0.30319'
            61:   action [:add, :config, :start]
            62:   thirty_two_bit true
            63:   pipeline_mode :Integrated
            64:   idle_timeout '00:00:00'
            65:   identity_type :ApplicationPoolIdentity 
            68:   load_user_profile false
            69: end
            70:

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/my/recipes/default.rb:59:in `from_file'

           iis_pool("My App Pool") do
             action [:add, :config, :start]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :iis_pool
             cookbook_name "my"
             recipe_name "default"
             runtime_version "4.0.30319"
             thirty_two_bit true
             pipeline_mode :Integrated
             idle_timeout "00:00:00"
             identity_type :ApplicationPoolIdentity
             appcmd "C:\\Windows\\System32\\inetsrv\\appcmd.exe"
           end

           Platform:
           ---------
           x64-mingw32

```

**Comment by fdzedzy** [comment]
I was just looking at this same problem.  The issue is that the pool name you are using has spaces in it. If there are no spaces, it is idempotent.  

Bug is here: https://github.com/chef-cookbooks/iis/blob/master/resources/pool.rb#L90

That line should be `cmd = shell_out("#{appcmd(node)} list apppool \"#{desired.name}\"")` like all the other times #{desired.name} is used.  I think it was just missed.

**Comment by EasyAsABC123** [comment]
good catch! @fdzedzy if you want to make a pull request with that and a test with the pool name having a space

**Comment by EasyAsABC123** [comment]
@fdzedzy let me know if you want to put in the PR otherwise i'll put one in with your catch

**Comment by fdzedzy** [comment]
@EasyAsABC123 Yup, just about to submit the PR.

**Comment by nitbrahul49** [comment]
still facing the same issue with cookbook version 7.1.0

Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '183'
       ---- Begin output of C:\Windows\System32\inetsrv\appcmd.exe add apppool /name:"my pool name" /managedRuntimeVersion:v4.0 /managedPipelineMode:Integrated /commit:\"MACHINE/WEBROOT/APPHOST\" ----
       STDOUT: ERROR ( message:Failed to add duplicate collection element "my pool name". )
       STDERR: 
       ---- End output of C:\Windows\System32\inetsrv\appcmd.exe add apppool /name:"my pool name" /managedRuntimeVersion:v4.0 /managedPipelineMode:Integrated /commit:\"MACHINE/WEBROOT/APPHOST\" ----
       Ran C:\Windows\System32\inetsrv\appcmd.exe add apppool /name:"my pool name" /managedRuntimeVersion:v4.0 /managedPipelineMode:Integrated /commit:\"MACHINE/WEBROOT/APPHOST\" returned 183
