### ISSUE TITLE
new_resource.identity should be new_resource.identity_type resources/pool.rb line 432 (i think)

### ISSUE THREAD

**Issue by stevenoneill** [chef-cookbooks/iis#360]
short version:::
check https://github.com/chef-cookbooks/iis/blob/master/resources/pool.rb#L432

new_resource.identity should be new_resource.identity_type right?

### Cookbook version
6.5.1

### Chef-client version
12.19.x

### Platform Details
Windows 2012 R2, iis 8.0

### Scenario:
iis_pool identity_type attribute not working

iis_pool 'anything' do
  identity_type :NetworkService
end

### Steps to Reproduce:
iis_pool 'anything' do
  identity_type :NetworkService
end

Observe in IIS Manager gui that pool Identity is ApplicaitonPoolIdentity and not NetworkService.

### Expected Result:
expecting identity to be NetworkService

### Actual Result:
Identity is set to ApplicationPoolIdentity

**Comment by EasyAsABC123** [comment]
Resolved by #362 in release [v6.5.2](https://github.com/chef-cookbooks/iis/pull/364)
