### ISSUE TITLE
iis_config not idempotent

### ISSUE THREAD

**Issue by scolligan** [chef-cookbooks/iis#366]
### Cookbook version
6.5.2

### Chef-client version
13.0.118

### Platform Details
Windows Server 2012 R2 on Azure

### Scenario:
The set action for iis_config executes each time chef client runs.

### Steps to Reproduce:
I used the example from the readme/help page:

# Sets up logging
iis_config "/section:system.applicationHost/sites /siteDefaults.logfile.directory:\"D:\\logs\"" do
    action :set
end

### Expected Result:
This should execute once.

### Actual Result:
This executes on each run of the chef client:

  * iis_config[/section:system.applicationHost/sites /siteDefaults.logfile.directory:"D:\logs"] action set[2017-05-16T16
:57:09-05:00] INFO: Processing iis_config[/section:system.applicationHost/sites /siteDefaults.logfile.directory:"D:\logs
"] action set (jjk_ts_transport_webserver::default line 41)

    - Executing IIS Config set

**Comment by EasyAsABC123** [comment]
Duplicate https://github.com/chef-cookbooks/iis/issues/276
