### ISSUE TITLE
Sporadic Issue with iis_pool idempotency

### ISSUE THREAD

**Issue by jakauppila** [chef-cookbooks/iis#416]
### Cookbook version
6.8.0

### Chef-client version
12.20.3

### Platform Details
Windows Server 2012 R2

### Scenario:
I am getting periodic failures on the iis_pool resource. When it attempts to load_current_value, it is encountering an error when executing `list apppool "pool_name"`.

I've been trying to troubleshoot this all day and haven't been getting anywhere.

### Steps to Reproduce:
The compiled Chef resource is in the Gist, https://gist.github.com/jakauppila/a3eaeed2b97c1a57b0400137ddcca98d

### Expected Result:
Converged completes successfully because on changes required to pool

### Actual Result:

https://gist.github.com/jakauppila/a3eaeed2b97c1a57b0400137ddcca98d

**Comment by jakauppila** [comment]
Disregard.

Elsewhere in the recipe I was modifying `C:\Windows\System32\inetsrv\config\schema\IISAdvancedLogging_schema.xml` via a `cookbook_file` as we are configuring a tab delimiter, and apparently `cookbook_file` creates a temporary file in the remote directly regardless on each run. It appears that was triggering an IIS reset or something when that occurred so it was periodically returning the error when trying to retrieve the app pool within a short timeframe.

**Comment by EasyAsABC123** [comment]
Thanks for keeping me in the know
