### ISSUE TITLE
IIS Default Logging

### ISSUE THREAD

**Issue by eelkram** [chef-cookbooks/iis#417]
### Cookbook version
6.8.0

### Chef-client version
13.8.5-1

### Platform Details
Windows Server 2016

### Scenario:
IIS can be configured with default log file settings on the server level.  If the per site settings are not configured then the website picks up the default settings.  The current site resource has a default value for log_directory which always overrides the server defaults even if nothing is passed to the resource. 

### Expected Result:
When no setting for log_directory is passed to the site resource it should not configure that settings thus inheriting from the server defaults.

### Options:
I would be happy to submit a PR to fix this as I have already made the change locally on a fork.  I wanted some feedback on which direction you would prefer and if you would accept the change.
1. Breaking Change - update log_directory to not have a default and not be configured if not set
2. Non Breaking Change - update log_directory when passed a blank value to not set the setting.  Since a blank string is an invalid log location this shouldn't break any existing implementation, but is kind-of Kludgy.
3. Some other option not presented.

**Comment by eelkram** [comment]
Okay, sounds like you would be more interested in the non breaking change option for a PR.  I'll take a look at the obsolete option, from my understanding I would need to make a different property name and then mark the current property with obsolete or am I missing something.

**Comment by EasyAsABC123** [comment]
yes you can do it that way or you can mark it obsolute then put in the readme that it will no longer have a default value.  i honestly would remove the default value and fix the behavior as it is a bug in my mind...but i'm sure someone has decided this is a feature.

**Comment by eelkram** [comment]
I think marking it as a bug is a fair assessment.  Also, since not setting the property would no longer configure the setting it wouldn't break a previously deployed server as it would leave whatever was previously configured.  I've submitted a PR for the fix.

**Comment by eelkram** [comment]
Excellent, thanks for the quick response and help on getting this fixed!
