### ISSUE TITLE
site LWRP current_resource.exists is sometimes incorrect (when there are a large number of bindings)

### ISSUE THREAD

**Issue by e100** [chef-cookbooks/iis#71]
There seems to be a bug in appcmd.exe that causes the output to fail when a site has a large number of bindings.

Some discussion of this appcmd bug here:
http://serverfault.com/questions/313339/appcmd-bugged-with-more-than-70ish-bindings

To avoid this problem the cookbook should replace the appcmd "list site" command with an alternate method to obtain the same data.

**Comment by EasyAsABC123** [comment]
@edmundcraske this is a possibility, however `appcmd` is extremely powerful.  Moving to powershell loses a lot backwards compatibility

**Comment by smurawski** [comment]
@e100 @edmundcraske @EasyAsABC123 I think there is a project working on that alongside this effort.  I'm not in love with appcmd, but the PowerShell story isn't much better.  Honestly, I think we should just go direct to the WMI api.  The problem with PowerShell is, unless it is made a requirement for a Chef install, it is an optional feature (even on the newer OS platforms) and can be uninstalled but IIS will continue to work.

Of course, this is an example of three people with three different preferred management techniques. :)  

As it stands, for the 3.x.x version, this cookbook will stick with appcmd.  

@e100 is the reported issue a blocker for you or just a potential problem?  If so, then we could look at replacing that particular method...

**Comment by e100** [comment]
This issue is not a blocker for me but it has bit me in the rear a few times when adding Chef to a previously manually configured server.

It is not necessary or desired to replace all appcmd calls, only this particular one.
Sure would be nice if MS would actually fix the bug in appcmd instead of us being forced to workaround their flaw.

**Comment by EasyAsABC123** [comment]
@e100 do you have a site you can send me via good old metabase explorer export?

If so, I think i might have a fix for this so i'd like to test but 70 bindings is a lot to type up.

**Comment by e100** [comment]
I have edited all of my sites bindings to resolve the problem. 

Fairly confident that its not 70+ bindings itself that causes this issue, its the totality of the data represented by all the bindings.  Maybe a few bindings with really long hostnames would be sufficient to trigger the issue.

**Comment by EasyAsABC123** [comment]
@e100 it appears using /xml solves this issue for large data results.  Still haven't had time to add 70 bindings...maybe i'll write a .bat script to just do it for me with an increment variable.

**Comment by EasyAsABC123** [comment]
@e100 closing issue, re-open if you have a metabase file that can show this is still and issue when using /output:xml
